#
#TODO: Add Punctuations, Special chars

tamil_ezhuthu = {
    'அ': {'ezhuthu': 'அ', 'name': 'அகரம்','vagai': 'உயிர்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2949]},
    'ஆ': {'ezhuthu': 'ஆ', 'name': 'ஆகாரம்', 'vagai': 'உயிர்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஆ', 'thaniEzhuthu': True, 'ucode': [2950]},
    'இ': {'ezhuthu': 'இ', 'name': 'இகரம்', 'vagai': 'உயிர்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'இ', 'thaniEzhuthu': True, 'ucode': [2951]},
    'ஈ': {'ezhuthu': 'ஈ', 'name': 'ஈகாரம்', 'vagai': 'உயிர்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஈ', 'thaniEzhuthu': True, 'ucode': [2952]},
    'உ': {'ezhuthu': 'உ', 'name': 'உகரம்', 'vagai': 'உயிர்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'உ', 'thaniEzhuthu': True, 'ucode': [2953]},
    'ஊ': {'ezhuthu': 'ஊ', 'name': 'ஊகாரம்', 'vagai': 'உயிர்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஊ', 'thaniEzhuthu': True, 'ucode': [2954]},
    'எ': {'ezhuthu': 'எ', 'name': 'எகரம்', 'vagai': 'உயிர்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'எ', 'thaniEzhuthu': True, 'ucode': [2958]},
    'ஏ': {'ezhuthu': 'ஏ', 'name': 'ஏகாரம்', 'vagai': 'உயிர்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஏ', 'thaniEzhuthu': True, 'ucode': [2959]},
    'ஐ': {'ezhuthu': 'ஐ', 'name': 'ஐகாரம்', 'vagai': 'உயிர்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஐ', 'thaniEzhuthu': True, 'ucode': [2960]},
    'ஒ': {'ezhuthu': 'ஒ', 'name': 'ஒகரம்', 'vagai': 'உயிர்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'ஒ', 'thaniEzhuthu': True, 'ucode': [2962]},
    'ஓ': {'ezhuthu': 'ஓ', 'name': 'ஓகாரம்', 'vagai': 'உயிர்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஓ', 'thaniEzhuthu': True, 'ucode': [2963]},
    'ஔ': {'ezhuthu': 'ஔ', 'name': 'ஒளகாரம்', 'vagai': 'உயிர்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஔ', 'thaniEzhuthu': True, 'ucode': [2964]},
    'க': {'ezhuthu': 'க', 'name': 'ககரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'வல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2965]},
    'ங': {'ezhuthu': 'ங', 'name': 'ஙகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'மெல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2969]},
    'ச': {'ezhuthu': 'ச', 'name': 'சகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'வல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2970]},
    'ஞ': {'ezhuthu': 'ஞ', 'name': 'ஞகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'மெல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2974]},
    'ட': {'ezhuthu': 'ட', 'name': 'டகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'வல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2975]},
    'ண': {'ezhuthu': 'ண', 'name': 'ணகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'மெல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2979]},
    'த': {'ezhuthu': 'த', 'name': 'தகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'வல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2980]},
    'ந': {'ezhuthu': 'ந', 'name': 'நகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'மெல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2984]},
    'ப': {'ezhuthu': 'ப', 'name': 'பகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'வல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2986]},
    'ம': {'ezhuthu': 'ம', 'name': 'மகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'மெல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2990]},
    'ய': {'ezhuthu': 'ய', 'name': 'யகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'இடையினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2991]},
    'ர': {'ezhuthu': 'ர', 'name': 'ரகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'இடையினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2992]},
    'ல': {'ezhuthu': 'ல', 'name': 'லகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'இடையினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2994]},
    'வ': {'ezhuthu': 'வ', 'name': 'வகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'இடையினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2997]},
    'ழ': {'ezhuthu': 'ழ', 'name': 'ழகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'இடையினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2996]},
    'ள': {'ezhuthu': 'ள', 'name': 'ளகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'இடையினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2995]},
    'ற': {'ezhuthu': 'ற', 'name': 'றகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'வல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2993]},
    'ன': {'ezhuthu': 'ன', 'name': 'னகரம்', 'vagai': 'உயிர்மெய்', 'alavu': 'குறில்', 'inam': 'மெல்லினம்', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2985]},
    '்': {'ezhuthu': '்', 'name': 'ஒற்று', 'vagai': 'துணையெழுத்து', 'alavu': 'ஒற்று', 'inam': '', 'uyir': '', 'thaniEzhuthu': False, 'ucode': [3021]},
    'ா': {'ezhuthu': 'ா', 'name': 'துணைக்கால்', 'vagai': 'துணையெழுத்து', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஆ', 'thaniEzhuthu': False, 'ucode': [3006]},
    'ி': {'ezhuthu': 'ி', 'name': 'மேல் விலங்கு', 'vagai': 'துணையெழுத்து', 'alavu': 'குறில்', 'inam': '', 'uyir': 'இ', 'thaniEzhuthu': False, 'ucode': [3007]},
    'ீ': {'ezhuthu': 'ீ', 'name': 'மேல் விலங்குச் சுழி', 'vagai': 'துணையெழுத்து', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஈ', 'thaniEzhuthu': False, 'ucode': [3008]},
    'ு': {'ezhuthu': 'ு', 'name': 'கீழ் விலங்கு', 'vagai': 'துணையெழுத்து', 'alavu': 'குறில்', 'inam': '', 'uyir': 'உ', 'thaniEzhuthu': False, 'ucode': [3009]},
    'ூ': {'ezhuthu': 'ூ', 'name': 'பின் வளை கீற்று', 'vagai': 'துணையெழுத்து', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஊ', 'thaniEzhuthu': False, 'ucode': [3010]},
    'ெ': {'ezhuthu': 'ெ', 'name': 'ஒற்றைக் கொம்பு', 'vagai': 'துணையெழுத்து', 'alavu': 'குறில்', 'inam': '', 'uyir': 'எ', 'thaniEzhuthu': False, 'ucode': [3014]},
    'ே': {'ezhuthu': 'ே', 'name': 'இரட்டைக் கொம்பு', 'vagai': 'துணையெழுத்து', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஏ', 'thaniEzhuthu': False, 'ucode': [3015]},
    'ை': {'ezhuthu': 'ை', 'name': 'இணைக்கொம்பு', 'vagai': 'துணையெழுத்து', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஐ', 'thaniEzhuthu': False, 'ucode': [3016]},
    'ொ': {'ezhuthu': 'ொ', 'name': 'ஒற்றைக் கொம்புக்கால்', 'vagai': 'துணையெழுத்து', 'alavu': 'குறில்', 'inam': '', 'uyir': 'ஒ', 'thaniEzhuthu': False, 'ucode': [3018]},
    'ோ': {'ezhuthu': 'ோ', 'name': 'இரட்டைக் கொம்புக்கால்', 'vagai': 'துணையெழுத்து', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஓ', 'thaniEzhuthu': False, 'ucode': [3019]},
    'ௌ': {'ezhuthu': 'ௌ', 'name': 'கொம்புக்கால் இணை', 'vagai': 'துணையெழுத்து', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஔ', 'thaniEzhuthu': False, 'ucode': [3020]},
    'ஃ': {'ezhuthu': 'ஃ', 'name': 'அஃகேனம்', 'vagai': 'ஆய்தம்', 'alavu': 'நெடில்', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [2947]},
    'ஜ': {'ezhuthu': 'ஜ', 'name': 'ஜகரம்', 'vagai': 'கிரந்தம்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2972]},
    'ஷ': {'ezhuthu': 'ஷ', 'name': 'ஷகரம்', 'vagai': 'கிரந்தம்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2999]},
    'ஸ': {'ezhuthu': 'ஸ', 'name': 'ஸகரம்', 'vagai': 'கிரந்தம்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [3000]},
    'ஹ': {'ezhuthu': 'ஹ', 'name': 'ஹகரம்', 'vagai': 'கிரந்தம்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [3001]},
    'ஶ': {'ezhuthu': 'ஶ', 'name': 'ஶகரம்', 'vagai': 'கிரந்தம்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2998]},
    'க்ஷ': {'ezhuthu': 'க்ஷ', 'name': 'க்ஷகரம்', 'vagai': 'கிரந்தம்', 'alavu': 'குறில்', 'inam': '', 'uyir': 'அ', 'thaniEzhuthu': True, 'ucode': [2965, 3021, 2999]},
    'ஸ்ரீ': {'ezhuthu': 'ஸ்ரீ', 'name': 'ஸ்ரீகாரம்', 'vagai': 'கிரந்தம்', 'alavu': 'நெடில்', 'inam': '', 'uyir': 'ஈ', 'thaniEzhuthu': True, 'ucode': [3000, 3021, 2992, 3008]},
    '௦': {'ezhuthu': '௦', 'name': 'சுழியம்', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3046]},
    '௧': {'ezhuthu': '௧', 'name': 'ஒன்று', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3047]},
    '௨': {'ezhuthu': '௨', 'name': 'இரண்டு', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3048]},
    '௩': {'ezhuthu': '௩', 'name': 'மூன்று', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3049]},
    '௪': {'ezhuthu': '௪', 'name': 'நான்கு', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3050]},
    '௫': {'ezhuthu': '௫', 'name': 'ஐந்து', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3051]},
    '௬': {'ezhuthu': '௬', 'name': 'ஆறு', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3052]},
    '௭': {'ezhuthu': '௭', 'name': 'ஏழு', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3053]},
    '௮': {'ezhuthu': '௮', 'name': 'எட்டு', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3054]},
    '௯': {'ezhuthu': '௯', 'name': 'ஒன்பது', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3055]},
    '௰': {'ezhuthu': '௰', 'name': 'பத்து', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3056]},
    '௱': {'ezhuthu': '௱', 'name': 'நூறு', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3057]},
    '௲': {'ezhuthu': '௲', 'name': 'ஆயிரம்', 'vagai': 'தமிழ் எண்', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3058]},
    '௳': {'ezhuthu': '௳', 'name': 'நாள்', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3059]},
    '௴': {'ezhuthu': '௴', 'name': 'மாதம்', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3060]},
    '௵': {'ezhuthu': '௵', 'name': 'வருடம்', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3061]},
    '௶': {'ezhuthu': '௶', 'name': 'செலவு', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3062]},
    '௷': {'ezhuthu': '௷', 'name': 'வரவு', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3063]},
    '௸': {'ezhuthu': '௸', 'name': 'மேலேயுள்ளபடி', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3064]},
    '௹': {'ezhuthu': '௹', 'name': 'ரூபாய்', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3065]},
    '௺': {'ezhuthu': '௺', 'name': 'இலக்கம்', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3066]},
    'ௐ': {'ezhuthu': 'ௐ', 'name': 'ஓங்காரம்', 'vagai': 'குறியீடு', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': True, 'ucode': [3024]},
}

empty_char = {'ezhuthu': '', 'name': '', 'vagai': '', 'alavu': '', 'inam': '', 'uyir': '', 'thaniEzhuthu': None, 'ucode': None}